version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.11
    commands:
      - pip install -r lf1/requirements.txt -t lf1/
      - pip install -r lf2/requirements.txt -t lf2/
  build:
    commands:
      - cd lf1 && zip -r ../lf1.zip . && cd ..
      - cd lf2 && zip -r ../lf2.zip . && cd ..
artifacts:
  files:
    - lf1.zip
    - lf2.zip
